### ISSUE TITLE
Buscando una API para el calculo de los costes de envío

### ISSUE THREAD

**Issue by UO258472** [Arquisoft/dede_es6c#110]
He encontrado una api que te calcula automaticamente costes de envio desde una direccion que le pases a otra (https://www.shipengine.com/), el problema está en que de momento para que te den la apikey tienes que crear una cuenta y una vez hecho esto iniciar sesión, pero dice que el correo no está verificado, pero tampoco te envían un correo de verificación.

**Comment by UO263595** [comment]
Se encontró la API Shippy, pero debido a los problemas encontrados en su utilización se descartó.

**Comment by UO258472** [comment]
Hemos probado también con la api Shippo, pero al final hemos optado por calcular nosotros los gastos de envío en base a las coordenadas, ya que en estas apis mencionadas solo podriamos realizar envíos en US y UK como mucho, después probamos con la api de Google, Geocoding API, pero al final nos decantamos por otra que se llama Mapbox.
