### ISSUE TITLE
Solucionar el problema con la navegación en el despliegue de AWS

### ISSUE THREAD

**Issue by UO258472** [Arquisoft/dede_es6c#164]
Podemos acceder a la ip/:3000 pero no podemos navegar por la aplicación.

**Comment by AGPAllStar** [comment]
Hay problemas con CORS a la hora de iniciar la aplicación, ya que no permite desde la IP de la máquina acceder a la api
@pglez82

**Comment by AGPAllStar** [comment]
No se pueden subir las imágenes de webapp a la máquina

**Comment by AGPAllStar** [comment]
Al arrancar la máquina con la aplicación en esta, no deja acceder
