### ISSUE TITLE
Correción hotspot cors

### ISSUE THREAD

**Issue by AGPAllStar** [Arquisoft/dede_es6c#188]
Se había dejado el método cors() sin opciones para probar la aplicación al desplegar, pero puede provocar ataques muy dañinos. Por eso hay que encontrar la forma de que funcione la aplicación y suprimir las vulnerabilidades provocadas

**Comment by UO258472** [comment]
Parece ser que al ponerle las opciones con Amazon Web Sevice tenemos que especificar que acepte todo lo que venga de 'http://*.compute-1.amazonaws.com:3000' pero internamente, la página intenta a acceder al localhost:5000 para cargar productos y el cors sigue bloqueandolo. Aún no hemos encontrado una solución a este problema
