### ISSUE TITLE
Despliegue Azure

### ISSUE THREAD

**Issue by uo269783** [Arquisoft/dede_es6c#235]
Intento de despliegue de la aplicación en Microsoft Azure, siguiendo las instrucciones del repositorio https://github.com/pglez82/asw2122_0 pero nuestra suscripción de alumnos no admite la creación de máquinas virtuales en East US.
![image](https://user-images.githubusercontent.com/71695163/166961632-8b62a695-45f0-47a4-9b01-6ff31bcc6fe1.png)

**Comment by UO258472** [comment]
Hemos tenido que crear una máquina de UK South para que funcionase, hemos hecho todo el proceso de creación e instalación de docker y desplegado nuestra app en Azure, pero nos encontramos con el mismo problema, una vez abiertos los puertos de azure, para https necesitamos un certificado, y nuestra cuenta de estudiantes no nos lo proporciona.
![image](https://user-images.githubusercontent.com/56638034/166972389-cbe7f303-e2cc-4153-a318-22d2d5df79b8.png)

![image](https://user-images.githubusercontent.com/56638034/166972473-a6d8140a-befd-4e42-9dd1-ab1624f78bd6.png)

**Comment by UO258472** [comment]
Hemos creado una dirección ip pública para redirigir el tráfico desde ella en https a nuestra app, pero no hemos logrado que de resultado.
![image](https://user-images.githubusercontent.com/56638034/166981582-973e2f6d-4dd2-492a-8a58-bb30db1b98f3.png)

Y un diseñador front door para redirigir el tráfico del backend al frontend
![image](https://user-images.githubusercontent.com/56638034/166982203-0f875e63-a084-4d29-aa2c-aaf3aaa600f1.png)
