### ISSUE TITLE
Despliegue de la aplicación funcionando

### ISSUE THREAD

**Issue by AGPAllStar** [Arquisoft/dede_es6c#237]
Este issue fue creado posteriormente a la entrega final del proyecto para solucionar lo del despliegue que se solicitó.
El despliegue se está realizando en Azure.

**Comment by AGPAllStar** [comment]
La aplicación está desplegada en Azure.
@labra 
@pglez82 
@cidinene 
@HugoLebredo 
Podéis encontrar el link en la página principal del repositorio (sección About), pero también se pasa por aquí:
- https://dedees6c.uksouth.cloudapp.azure.com:3000/

**Comment by cidinene** [comment]
Probado con renault megane y me funciona

**Comment by pglez82** [comment]
Yo también he podido hacer un pedido almacenando la dirección en notas.

**Comment by labra** [comment]
También lo he probado y me funcionó.

**Comment by HugoLebredo** [comment]
Todo correcto. Buen trabajo

**Comment by AGPAllStar** [comment]
El issue se ha cerrado debido a la aprobación de los profesores
